/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 3eb6203fab3e398eec448c7f2373a557)
interface __BaseEnv_Env {
	VITE_SUPABASE_URL: string;
	VITE_SUPABASE_ANON_KEY: string;
	VITE_APP_URL: string;
	VITE_MOBILE_APP_SCHEME: string;
	VITE_POSTHOG_KEY: string;
	VITE_POSTHOG_HOST: string;
	SUPABASE_URL: string;
	SUPABASE_ANON_KEY: string;
	APP_URL: string;
	ADMIN_URL: string;
	MOBILE_APP_SCHEME: string;
	CLOUDFLARE_ACCOUNT_ID: string;
	CLOUDFLARE_CUSTOMER_SUBDOMAIN: string;
	STRIPE_PUBLISHABLE_KEY: string;
	STRIPE_BEGINNER_PRICE_ID: string;
	STRIPE_INTERMEDIATE_PRICE_ID: string;
	STRIPE_ADVANCED_PRICE_ID: string;
	API_RATE_LIMITER: RateLimit;
	ADMIN_RATE_LIMITER: RateLimit;
	AUTH_RATE_LIMITER: RateLimit;
}
declare namespace Cloudflare {
	interface StagingEnv {
		VITE_SUPABASE_URL: string;
		VITE_SUPABASE_ANON_KEY: string;
		VITE_APP_URL: string;
		VITE_MOBILE_APP_SCHEME: string;
		VITE_POSTHOG_KEY: string;
		VITE_POSTHOG_HOST: string;
		SUPABASE_URL: string;
		SUPABASE_ANON_KEY: string;
		APP_URL: string;
		ADMIN_URL: string;
		MOBILE_APP_SCHEME: string;
		CLOUDFLARE_ACCOUNT_ID: string;
		CLOUDFLARE_CUSTOMER_SUBDOMAIN: string;
		STRIPE_PUBLISHABLE_KEY: string;
		STRIPE_BEGINNER_PRICE_ID: string;
		STRIPE_INTERMEDIATE_PRICE_ID: string;
		STRIPE_ADVANCED_PRICE_ID: string;
		API_RATE_LIMITER: RateLimit;
		ADMIN_RATE_LIMITER: RateLimit;
		AUTH_RATE_LIMITER: RateLimit;
	}
	interface PreviewEnv {
		VITE_SUPABASE_URL: string;
		VITE_SUPABASE_ANON_KEY: string;
		VITE_APP_URL: string;
		VITE_MOBILE_APP_SCHEME: string;
		VITE_POSTHOG_KEY: string;
		VITE_POSTHOG_HOST: string;
		SUPABASE_URL: string;
		SUPABASE_ANON_KEY: string;
		APP_URL: string;
		ADMIN_URL: string;
		MOBILE_APP_SCHEME: string;
		CLOUDFLARE_ACCOUNT_ID: string;
		CLOUDFLARE_CUSTOMER_SUBDOMAIN: string;
		STRIPE_PUBLISHABLE_KEY: string;
		STRIPE_BEGINNER_PRICE_ID: string;
		STRIPE_INTERMEDIATE_PRICE_ID: string;
		STRIPE_ADVANCED_PRICE_ID: string;
		API_RATE_LIMITER: RateLimit;
		ADMIN_RATE_LIMITER: RateLimit;
		AUTH_RATE_LIMITER: RateLimit;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "VITE_SUPABASE_URL" | "VITE_SUPABASE_ANON_KEY" | "VITE_APP_URL" | "VITE_MOBILE_APP_SCHEME" | "VITE_POSTHOG_KEY" | "VITE_POSTHOG_HOST" | "SUPABASE_URL" | "SUPABASE_ANON_KEY" | "APP_URL" | "ADMIN_URL" | "MOBILE_APP_SCHEME" | "CLOUDFLARE_ACCOUNT_ID" | "CLOUDFLARE_CUSTOMER_SUBDOMAIN" | "STRIPE_PUBLISHABLE_KEY" | "STRIPE_BEGINNER_PRICE_ID" | "STRIPE_INTERMEDIATE_PRICE_ID" | "STRIPE_ADVANCED_PRICE_ID">> {}
}
