/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: a404f8dead629b9b9f3bd27249d18993)
interface __BaseEnv_Env {
	VITE_SUPABASE_URL: "https://TODO.supabase.co";
	VITE_SUPABASE_ANON_KEY: "TODO";
	VITE_APP_URL: "https://evolution-combatives-admin-staging.jesse-6b1.workers.dev" | "https://evolution-combatives-admin-preview.jesse-6b1.workers.dev" | "https://admin.evolutioncombatives.com";
	VITE_MOBILE_APP_SCHEME: "evolutioncombatives";
	VITE_POSTHOG_KEY: "TODO";
	VITE_POSTHOG_HOST: "https://us.i.posthog.com";
	SUPABASE_URL: "https://TODO.supabase.co";
	SUPABASE_ANON_KEY: "TODO";
	APP_URL: "https://evolution-combatives-admin-staging.jesse-6b1.workers.dev" | "https://evolution-combatives-admin-preview.jesse-6b1.workers.dev" | "https://admin.evolutioncombatives.com";
	ADMIN_URL: "https://evolution-combatives-admin-staging.jesse-6b1.workers.dev" | "https://evolution-combatives-admin-preview.jesse-6b1.workers.dev" | "https://admin.evolutioncombatives.com";
	MOBILE_APP_SCHEME: "evolutioncombatives";
	CLOUDFLARE_ACCOUNT_ID: "TODO-stream-account-id";
	CLOUDFLARE_CUSTOMER_SUBDOMAIN: "TODO.cloudflarestream.com";
	STRIPE_PUBLISHABLE_KEY: "pk_test_TODO" | "pk_live_TODO";
	STRIPE_BEGINNER_PRICE_ID: "price_TODO";
	STRIPE_INTERMEDIATE_PRICE_ID: "price_TODO";
	STRIPE_ADVANCED_PRICE_ID: "price_TODO";
	API_RATE_LIMITER: RateLimit;
	ADMIN_RATE_LIMITER: RateLimit;
	AUTH_RATE_LIMITER: RateLimit;
}
declare namespace Cloudflare {
	interface StagingEnv {
		VITE_SUPABASE_URL: "https://TODO.supabase.co";
		VITE_SUPABASE_ANON_KEY: "TODO";
		VITE_APP_URL: "https://evolution-combatives-admin-staging.jesse-6b1.workers.dev";
		VITE_MOBILE_APP_SCHEME: "evolutioncombatives";
		VITE_POSTHOG_KEY: "TODO";
		VITE_POSTHOG_HOST: "https://us.i.posthog.com";
		SUPABASE_URL: "https://TODO.supabase.co";
		SUPABASE_ANON_KEY: "TODO";
		APP_URL: "https://evolution-combatives-admin-staging.jesse-6b1.workers.dev";
		ADMIN_URL: "https://evolution-combatives-admin-staging.jesse-6b1.workers.dev";
		MOBILE_APP_SCHEME: "evolutioncombatives";
		CLOUDFLARE_ACCOUNT_ID: "TODO-stream-account-id";
		CLOUDFLARE_CUSTOMER_SUBDOMAIN: "TODO.cloudflarestream.com";
		STRIPE_PUBLISHABLE_KEY: "pk_test_TODO";
		STRIPE_BEGINNER_PRICE_ID: "price_TODO";
		STRIPE_INTERMEDIATE_PRICE_ID: "price_TODO";
		STRIPE_ADVANCED_PRICE_ID: "price_TODO";
		API_RATE_LIMITER: RateLimit;
		ADMIN_RATE_LIMITER: RateLimit;
		AUTH_RATE_LIMITER: RateLimit;
	}
	interface PreviewEnv {
		VITE_SUPABASE_URL: "https://TODO.supabase.co";
		VITE_SUPABASE_ANON_KEY: "TODO";
		VITE_APP_URL: "https://evolution-combatives-admin-preview.jesse-6b1.workers.dev";
		VITE_MOBILE_APP_SCHEME: "evolutioncombatives";
		VITE_POSTHOG_KEY: "TODO";
		VITE_POSTHOG_HOST: "https://us.i.posthog.com";
		SUPABASE_URL: "https://TODO.supabase.co";
		SUPABASE_ANON_KEY: "TODO";
		APP_URL: "https://evolution-combatives-admin-preview.jesse-6b1.workers.dev";
		ADMIN_URL: "https://evolution-combatives-admin-preview.jesse-6b1.workers.dev";
		MOBILE_APP_SCHEME: "evolutioncombatives";
		CLOUDFLARE_ACCOUNT_ID: "TODO-stream-account-id";
		CLOUDFLARE_CUSTOMER_SUBDOMAIN: "TODO.cloudflarestream.com";
		STRIPE_PUBLISHABLE_KEY: "pk_test_TODO";
		STRIPE_BEGINNER_PRICE_ID: "price_TODO";
		STRIPE_INTERMEDIATE_PRICE_ID: "price_TODO";
		STRIPE_ADVANCED_PRICE_ID: "price_TODO";
		API_RATE_LIMITER: RateLimit;
		ADMIN_RATE_LIMITER: RateLimit;
		AUTH_RATE_LIMITER: RateLimit;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "VITE_SUPABASE_URL" | "VITE_SUPABASE_ANON_KEY" | "VITE_APP_URL" | "VITE_MOBILE_APP_SCHEME" | "VITE_POSTHOG_KEY" | "VITE_POSTHOG_HOST" | "SUPABASE_URL" | "SUPABASE_ANON_KEY" | "APP_URL" | "ADMIN_URL" | "MOBILE_APP_SCHEME" | "CLOUDFLARE_ACCOUNT_ID" | "CLOUDFLARE_CUSTOMER_SUBDOMAIN" | "STRIPE_PUBLISHABLE_KEY" | "STRIPE_BEGINNER_PRICE_ID" | "STRIPE_INTERMEDIATE_PRICE_ID" | "STRIPE_ADVANCED_PRICE_ID">> {}
}
