/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCsrfTokenRouteImport } from './routes/api/csrf-token'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as IngestSplatRouteImport } from './routes/ingest.$'
import { Route as ApiWebhooksCloudflareRouteImport } from './routes/api/webhooks/cloudflare'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api/webhooks/stripe'
import { Route as ApiMobileSubscriptionsCreateCheckoutRouteImport } from './routes/api/mobile/subscriptions/create-checkout'
import { Route as ApiMobileVideoSignedUrlRouteImport } from './routes/api/mobile/video/signed-url'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCsrfTokenRoute = ApiCsrfTokenRouteImport.update({
  id: '/api/csrf-token',
  path: '/api/csrf-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const IngestSplatRoute = IngestSplatRouteImport.update({
  id: '/ingest/$',
  path: '/ingest/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksCloudflareRoute = ApiWebhooksCloudflareRouteImport.update({
  id: '/api/webhooks/cloudflare',
  path: '/api/webhooks/cloudflare',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileSubscriptionsCreateCheckoutRoute =
  ApiMobileSubscriptionsCreateCheckoutRouteImport.update({
    id: '/api/mobile/subscriptions/create-checkout',
    path: '/api/mobile/subscriptions/create-checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMobileVideoSignedUrlRoute = ApiMobileVideoSignedUrlRouteImport.update({
  id: '/api/mobile/video/signed-url',
  path: '/api/mobile/video/signed-url',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/csrf-token': typeof ApiCsrfTokenRoute
  '/api/health': typeof ApiHealthRoute
  '/ingest/$': typeof IngestSplatRoute
  '/api/webhooks/cloudflare': typeof ApiWebhooksCloudflareRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/api/mobile/subscriptions/create-checkout': typeof ApiMobileSubscriptionsCreateCheckoutRoute
  '/api/mobile/video/signed-url': typeof ApiMobileVideoSignedUrlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/csrf-token': typeof ApiCsrfTokenRoute
  '/api/health': typeof ApiHealthRoute
  '/ingest/$': typeof IngestSplatRoute
  '/api/webhooks/cloudflare': typeof ApiWebhooksCloudflareRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/api/mobile/subscriptions/create-checkout': typeof ApiMobileSubscriptionsCreateCheckoutRoute
  '/api/mobile/video/signed-url': typeof ApiMobileVideoSignedUrlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/csrf-token': typeof ApiCsrfTokenRoute
  '/api/health': typeof ApiHealthRoute
  '/ingest/$': typeof IngestSplatRoute
  '/api/webhooks/cloudflare': typeof ApiWebhooksCloudflareRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/api/mobile/subscriptions/create-checkout': typeof ApiMobileSubscriptionsCreateCheckoutRoute
  '/api/mobile/video/signed-url': typeof ApiMobileVideoSignedUrlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/csrf-token'
    | '/api/health'
    | '/ingest/$'
    | '/api/webhooks/cloudflare'
    | '/api/webhooks/stripe'
    | '/api/mobile/subscriptions/create-checkout'
    | '/api/mobile/video/signed-url'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/csrf-token'
    | '/api/health'
    | '/ingest/$'
    | '/api/webhooks/cloudflare'
    | '/api/webhooks/stripe'
    | '/api/mobile/subscriptions/create-checkout'
    | '/api/mobile/video/signed-url'
  id:
    | '__root__'
    | '/'
    | '/api/csrf-token'
    | '/api/health'
    | '/ingest/$'
    | '/api/webhooks/cloudflare'
    | '/api/webhooks/stripe'
    | '/api/mobile/subscriptions/create-checkout'
    | '/api/mobile/video/signed-url'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCsrfTokenRoute: typeof ApiCsrfTokenRoute
  ApiHealthRoute: typeof ApiHealthRoute
  IngestSplatRoute: typeof IngestSplatRoute
  ApiWebhooksCloudflareRoute: typeof ApiWebhooksCloudflareRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
  ApiMobileSubscriptionsCreateCheckoutRoute: typeof ApiMobileSubscriptionsCreateCheckoutRoute
  ApiMobileVideoSignedUrlRoute: typeof ApiMobileVideoSignedUrlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/csrf-token': {
      id: '/api/csrf-token'
      path: '/api/csrf-token'
      fullPath: '/api/csrf-token'
      preLoaderRoute: typeof ApiCsrfTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingest/$': {
      id: '/ingest/$'
      path: '/ingest/$'
      fullPath: '/ingest/$'
      preLoaderRoute: typeof IngestSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/cloudflare': {
      id: '/api/webhooks/cloudflare'
      path: '/api/webhooks/cloudflare'
      fullPath: '/api/webhooks/cloudflare'
      preLoaderRoute: typeof ApiWebhooksCloudflareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/subscriptions/create-checkout': {
      id: '/api/mobile/subscriptions/create-checkout'
      path: '/api/mobile/subscriptions/create-checkout'
      fullPath: '/api/mobile/subscriptions/create-checkout'
      preLoaderRoute: typeof ApiMobileSubscriptionsCreateCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/video/signed-url': {
      id: '/api/mobile/video/signed-url'
      path: '/api/mobile/video/signed-url'
      fullPath: '/api/mobile/video/signed-url'
      preLoaderRoute: typeof ApiMobileVideoSignedUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCsrfTokenRoute: ApiCsrfTokenRoute,
  ApiHealthRoute: ApiHealthRoute,
  IngestSplatRoute: IngestSplatRoute,
  ApiWebhooksCloudflareRoute: ApiWebhooksCloudflareRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
  ApiMobileSubscriptionsCreateCheckoutRoute:
    ApiMobileSubscriptionsCreateCheckoutRoute,
  ApiMobileVideoSignedUrlRoute: ApiMobileVideoSignedUrlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
